/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutputsAndIndicatorsRouteImport } from './routes/outputs-and-indicators'
import { Route as IndicatorVisualizationRouteImport } from './routes/indicator-visualization'
import { Route as DataManagementRouteImport } from './routes/data-management'
import { Route as BaselineMappingRouteImport } from './routes/baseline-mapping'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards.index'
import { Route as OutputsAndIndicatorsOutputsRouteImport } from './routes/outputs-and-indicators.outputs'
import { Route as OutputsAndIndicatorsIndicatorsRouteImport } from './routes/outputs-and-indicators.indicators'
import { Route as DataManagementImportRouteImport } from './routes/data-management.import'
import { Route as DashboardsAddRouteImport } from './routes/dashboards.add'
import { Route as DashboardsDashboardIdRouteImport } from './routes/dashboards.$dashboardId'
import { Route as DashboardsDashboardIdManageRouteImport } from './routes/dashboards.$dashboardId.manage'
import { Route as DashboardsDashboardIdEditRouteImport } from './routes/dashboards.$dashboardId.edit'

const OutputsAndIndicatorsRoute = OutputsAndIndicatorsRouteImport.update({
  id: '/outputs-and-indicators',
  path: '/outputs-and-indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorVisualizationRoute = IndicatorVisualizationRouteImport.update({
  id: '/indicator-visualization',
  path: '/indicator-visualization',
  getParentRoute: () => rootRouteImport,
} as any)
const DataManagementRoute = DataManagementRouteImport.update({
  id: '/data-management',
  path: '/data-management',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineMappingRoute = BaselineMappingRouteImport.update({
  id: '/baseline-mapping',
  path: '/baseline-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsAndIndicatorsOutputsRoute =
  OutputsAndIndicatorsOutputsRouteImport.update({
    id: '/outputs',
    path: '/outputs',
    getParentRoute: () => OutputsAndIndicatorsRoute,
  } as any)
const OutputsAndIndicatorsIndicatorsRoute =
  OutputsAndIndicatorsIndicatorsRouteImport.update({
    id: '/indicators',
    path: '/indicators',
    getParentRoute: () => OutputsAndIndicatorsRoute,
  } as any)
const DataManagementImportRoute = DataManagementImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DataManagementRoute,
} as any)
const DashboardsAddRoute = DashboardsAddRouteImport.update({
  id: '/dashboards/add',
  path: '/dashboards/add',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdManageRoute =
  DashboardsDashboardIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => DashboardsDashboardIdRoute,
  } as any)
const DashboardsDashboardIdEditRoute =
  DashboardsDashboardIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardsDashboardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baseline-mapping': typeof BaselineMappingRoute
  '/data-management': typeof DataManagementRouteWithChildren
  '/indicator-visualization': typeof IndicatorVisualizationRoute
  '/outputs-and-indicators': typeof OutputsAndIndicatorsRouteWithChildren
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/dashboards/add': typeof DashboardsAddRoute
  '/data-management/import': typeof DataManagementImportRoute
  '/outputs-and-indicators/indicators': typeof OutputsAndIndicatorsIndicatorsRoute
  '/outputs-and-indicators/outputs': typeof OutputsAndIndicatorsOutputsRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/dashboards/$dashboardId/manage': typeof DashboardsDashboardIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baseline-mapping': typeof BaselineMappingRoute
  '/data-management': typeof DataManagementRouteWithChildren
  '/indicator-visualization': typeof IndicatorVisualizationRoute
  '/outputs-and-indicators': typeof OutputsAndIndicatorsRouteWithChildren
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/dashboards/add': typeof DashboardsAddRoute
  '/data-management/import': typeof DataManagementImportRoute
  '/outputs-and-indicators/indicators': typeof OutputsAndIndicatorsIndicatorsRoute
  '/outputs-and-indicators/outputs': typeof OutputsAndIndicatorsOutputsRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/dashboards/$dashboardId/manage': typeof DashboardsDashboardIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baseline-mapping': typeof BaselineMappingRoute
  '/data-management': typeof DataManagementRouteWithChildren
  '/indicator-visualization': typeof IndicatorVisualizationRoute
  '/outputs-and-indicators': typeof OutputsAndIndicatorsRouteWithChildren
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/dashboards/add': typeof DashboardsAddRoute
  '/data-management/import': typeof DataManagementImportRoute
  '/outputs-and-indicators/indicators': typeof OutputsAndIndicatorsIndicatorsRoute
  '/outputs-and-indicators/outputs': typeof OutputsAndIndicatorsOutputsRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/dashboards/$dashboardId/manage': typeof DashboardsDashboardIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baseline-mapping'
    | '/data-management'
    | '/indicator-visualization'
    | '/outputs-and-indicators'
    | '/dashboards/$dashboardId'
    | '/dashboards/add'
    | '/data-management/import'
    | '/outputs-and-indicators/indicators'
    | '/outputs-and-indicators/outputs'
    | '/dashboards/'
    | '/dashboards/$dashboardId/edit'
    | '/dashboards/$dashboardId/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baseline-mapping'
    | '/data-management'
    | '/indicator-visualization'
    | '/outputs-and-indicators'
    | '/dashboards/$dashboardId'
    | '/dashboards/add'
    | '/data-management/import'
    | '/outputs-and-indicators/indicators'
    | '/outputs-and-indicators/outputs'
    | '/dashboards'
    | '/dashboards/$dashboardId/edit'
    | '/dashboards/$dashboardId/manage'
  id:
    | '__root__'
    | '/'
    | '/baseline-mapping'
    | '/data-management'
    | '/indicator-visualization'
    | '/outputs-and-indicators'
    | '/dashboards/$dashboardId'
    | '/dashboards/add'
    | '/data-management/import'
    | '/outputs-and-indicators/indicators'
    | '/outputs-and-indicators/outputs'
    | '/dashboards/'
    | '/dashboards/$dashboardId/edit'
    | '/dashboards/$dashboardId/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaselineMappingRoute: typeof BaselineMappingRoute
  DataManagementRoute: typeof DataManagementRouteWithChildren
  IndicatorVisualizationRoute: typeof IndicatorVisualizationRoute
  OutputsAndIndicatorsRoute: typeof OutputsAndIndicatorsRouteWithChildren
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRouteWithChildren
  DashboardsAddRoute: typeof DashboardsAddRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/outputs-and-indicators': {
      id: '/outputs-and-indicators'
      path: '/outputs-and-indicators'
      fullPath: '/outputs-and-indicators'
      preLoaderRoute: typeof OutputsAndIndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicator-visualization': {
      id: '/indicator-visualization'
      path: '/indicator-visualization'
      fullPath: '/indicator-visualization'
      preLoaderRoute: typeof IndicatorVisualizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-management': {
      id: '/data-management'
      path: '/data-management'
      fullPath: '/data-management'
      preLoaderRoute: typeof DataManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline-mapping': {
      id: '/baseline-mapping'
      path: '/baseline-mapping'
      fullPath: '/baseline-mapping'
      preLoaderRoute: typeof BaselineMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs-and-indicators/outputs': {
      id: '/outputs-and-indicators/outputs'
      path: '/outputs'
      fullPath: '/outputs-and-indicators/outputs'
      preLoaderRoute: typeof OutputsAndIndicatorsOutputsRouteImport
      parentRoute: typeof OutputsAndIndicatorsRoute
    }
    '/outputs-and-indicators/indicators': {
      id: '/outputs-and-indicators/indicators'
      path: '/indicators'
      fullPath: '/outputs-and-indicators/indicators'
      preLoaderRoute: typeof OutputsAndIndicatorsIndicatorsRouteImport
      parentRoute: typeof OutputsAndIndicatorsRoute
    }
    '/data-management/import': {
      id: '/data-management/import'
      path: '/import'
      fullPath: '/data-management/import'
      preLoaderRoute: typeof DataManagementImportRouteImport
      parentRoute: typeof DataManagementRoute
    }
    '/dashboards/add': {
      id: '/dashboards/add'
      path: '/dashboards/add'
      fullPath: '/dashboards/add'
      preLoaderRoute: typeof DashboardsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId/manage': {
      id: '/dashboards/$dashboardId/manage'
      path: '/manage'
      fullPath: '/dashboards/$dashboardId/manage'
      preLoaderRoute: typeof DashboardsDashboardIdManageRouteImport
      parentRoute: typeof DashboardsDashboardIdRoute
    }
    '/dashboards/$dashboardId/edit': {
      id: '/dashboards/$dashboardId/edit'
      path: '/edit'
      fullPath: '/dashboards/$dashboardId/edit'
      preLoaderRoute: typeof DashboardsDashboardIdEditRouteImport
      parentRoute: typeof DashboardsDashboardIdRoute
    }
  }
}

interface DataManagementRouteChildren {
  DataManagementImportRoute: typeof DataManagementImportRoute
}

const DataManagementRouteChildren: DataManagementRouteChildren = {
  DataManagementImportRoute: DataManagementImportRoute,
}

const DataManagementRouteWithChildren = DataManagementRoute._addFileChildren(
  DataManagementRouteChildren,
)

interface OutputsAndIndicatorsRouteChildren {
  OutputsAndIndicatorsIndicatorsRoute: typeof OutputsAndIndicatorsIndicatorsRoute
  OutputsAndIndicatorsOutputsRoute: typeof OutputsAndIndicatorsOutputsRoute
}

const OutputsAndIndicatorsRouteChildren: OutputsAndIndicatorsRouteChildren = {
  OutputsAndIndicatorsIndicatorsRoute: OutputsAndIndicatorsIndicatorsRoute,
  OutputsAndIndicatorsOutputsRoute: OutputsAndIndicatorsOutputsRoute,
}

const OutputsAndIndicatorsRouteWithChildren =
  OutputsAndIndicatorsRoute._addFileChildren(OutputsAndIndicatorsRouteChildren)

interface DashboardsDashboardIdRouteChildren {
  DashboardsDashboardIdEditRoute: typeof DashboardsDashboardIdEditRoute
  DashboardsDashboardIdManageRoute: typeof DashboardsDashboardIdManageRoute
}

const DashboardsDashboardIdRouteChildren: DashboardsDashboardIdRouteChildren = {
  DashboardsDashboardIdEditRoute: DashboardsDashboardIdEditRoute,
  DashboardsDashboardIdManageRoute: DashboardsDashboardIdManageRoute,
}

const DashboardsDashboardIdRouteWithChildren =
  DashboardsDashboardIdRoute._addFileChildren(
    DashboardsDashboardIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaselineMappingRoute: BaselineMappingRoute,
  DataManagementRoute: DataManagementRouteWithChildren,
  IndicatorVisualizationRoute: IndicatorVisualizationRoute,
  OutputsAndIndicatorsRoute: OutputsAndIndicatorsRouteWithChildren,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRouteWithChildren,
  DashboardsAddRoute: DashboardsAddRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
