/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OutputsAndIndicatorsRouteImport } from './routes/outputs-and-indicators'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndicatorVisualizationRouteImport } from './routes/indicator-visualization'
import { Route as DataQualityRouteImport } from './routes/data-quality'
import { Route as DataManagementRouteImport } from './routes/data-management'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as BaselineMappingRouteImport } from './routes/baseline-mapping'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as MappingsIndexRouteImport } from './routes/mappings.index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards.index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as OutputsAndIndicatorsOutputsRouteImport } from './routes/outputs-and-indicators.outputs'
import { Route as OutputsAndIndicatorsIndicatorsRouteImport } from './routes/outputs-and-indicators.indicators'
import { Route as MappingsAddRouteImport } from './routes/mappings.add'
import { Route as MappingsMappingIdRouteImport } from './routes/mappings.$mappingId'
import { Route as DataManagementImportRouteImport } from './routes/data-management.import'
import { Route as DashboardsAddRouteImport } from './routes/dashboards.add'
import { Route as DashboardsDashboardIdRouteImport } from './routes/dashboards.$dashboardId'
import { Route as ConnectionsConnectionIdRouteImport } from './routes/connections.$connectionId'
import { Route as DashboardsDashboardIdPreviewRouteImport } from './routes/dashboards.$dashboardId.preview'
import { Route as DashboardsDashboardIdManageRouteImport } from './routes/dashboards.$dashboardId.manage'
import { Route as DashboardsDashboardIdEditRouteImport } from './routes/dashboards.$dashboardId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsAndIndicatorsRoute = OutputsAndIndicatorsRouteImport.update({
  id: '/outputs-and-indicators',
  path: '/outputs-and-indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorVisualizationRoute = IndicatorVisualizationRouteImport.update({
  id: '/indicator-visualization',
  path: '/indicator-visualization',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityRoute = DataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const DataManagementRoute = DataManagementRouteImport.update({
  id: '/data-management',
  path: '/data-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineMappingRoute = BaselineMappingRouteImport.update({
  id: '/baseline-mapping',
  path: '/baseline-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingsIndexRoute = MappingsIndexRouteImport.update({
  id: '/mappings/',
  path: '/mappings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsAndIndicatorsOutputsRoute =
  OutputsAndIndicatorsOutputsRouteImport.update({
    id: '/outputs',
    path: '/outputs',
    getParentRoute: () => OutputsAndIndicatorsRoute,
  } as any)
const OutputsAndIndicatorsIndicatorsRoute =
  OutputsAndIndicatorsIndicatorsRouteImport.update({
    id: '/indicators',
    path: '/indicators',
    getParentRoute: () => OutputsAndIndicatorsRoute,
  } as any)
const MappingsAddRoute = MappingsAddRouteImport.update({
  id: '/mappings/add',
  path: '/mappings/add',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingsMappingIdRoute = MappingsMappingIdRouteImport.update({
  id: '/mappings/$mappingId',
  path: '/mappings/$mappingId',
  getParentRoute: () => rootRouteImport,
} as any)
const DataManagementImportRoute = DataManagementImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DataManagementRoute,
} as any)
const DashboardsAddRoute = DashboardsAddRouteImport.update({
  id: '/dashboards/add',
  path: '/dashboards/add',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsConnectionIdRoute = ConnectionsConnectionIdRouteImport.update({
  id: '/$connectionId',
  path: '/$connectionId',
  getParentRoute: () => ConnectionsRoute,
} as any)
const DashboardsDashboardIdPreviewRoute =
  DashboardsDashboardIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => DashboardsDashboardIdRoute,
  } as any)
const DashboardsDashboardIdManageRoute =
  DashboardsDashboardIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => DashboardsDashboardIdRoute,
  } as any)
const DashboardsDashboardIdEditRoute =
  DashboardsDashboardIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardsDashboardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/baseline-mapping': typeof BaselineMappingRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/data-management': typeof DataManagementRouteWithChildren
  '/data-quality': typeof DataQualityRoute
  '/indicator-visualization': typeof IndicatorVisualizationRoute
  '/login': typeof LoginRoute
  '/outputs-and-indicators': typeof OutputsAndIndicatorsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/dashboards/add': typeof DashboardsAddRoute
  '/data-management/import': typeof DataManagementImportRoute
  '/mappings/$mappingId': typeof MappingsMappingIdRoute
  '/mappings/add': typeof MappingsAddRoute
  '/outputs-and-indicators/indicators': typeof OutputsAndIndicatorsIndicatorsRoute
  '/outputs-and-indicators/outputs': typeof OutputsAndIndicatorsOutputsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/mappings/': typeof MappingsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/dashboards/$dashboardId/manage': typeof DashboardsDashboardIdManageRoute
  '/dashboards/$dashboardId/preview': typeof DashboardsDashboardIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/baseline-mapping': typeof BaselineMappingRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/data-management': typeof DataManagementRouteWithChildren
  '/data-quality': typeof DataQualityRoute
  '/indicator-visualization': typeof IndicatorVisualizationRoute
  '/login': typeof LoginRoute
  '/outputs-and-indicators': typeof OutputsAndIndicatorsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/dashboards/add': typeof DashboardsAddRoute
  '/data-management/import': typeof DataManagementImportRoute
  '/mappings/$mappingId': typeof MappingsMappingIdRoute
  '/mappings/add': typeof MappingsAddRoute
  '/outputs-and-indicators/indicators': typeof OutputsAndIndicatorsIndicatorsRoute
  '/outputs-and-indicators/outputs': typeof OutputsAndIndicatorsOutputsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/mappings': typeof MappingsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/dashboards/$dashboardId/manage': typeof DashboardsDashboardIdManageRoute
  '/dashboards/$dashboardId/preview': typeof DashboardsDashboardIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/baseline-mapping': typeof BaselineMappingRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/data-management': typeof DataManagementRouteWithChildren
  '/data-quality': typeof DataQualityRoute
  '/indicator-visualization': typeof IndicatorVisualizationRoute
  '/login': typeof LoginRoute
  '/outputs-and-indicators': typeof OutputsAndIndicatorsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/dashboards/add': typeof DashboardsAddRoute
  '/data-management/import': typeof DataManagementImportRoute
  '/mappings/$mappingId': typeof MappingsMappingIdRoute
  '/mappings/add': typeof MappingsAddRoute
  '/outputs-and-indicators/indicators': typeof OutputsAndIndicatorsIndicatorsRoute
  '/outputs-and-indicators/outputs': typeof OutputsAndIndicatorsOutputsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/mappings/': typeof MappingsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/dashboards/$dashboardId/manage': typeof DashboardsDashboardIdManageRoute
  '/dashboards/$dashboardId/preview': typeof DashboardsDashboardIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/baseline-mapping'
    | '/connections'
    | '/data-management'
    | '/data-quality'
    | '/indicator-visualization'
    | '/login'
    | '/outputs-and-indicators'
    | '/pricing'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/connections/$connectionId'
    | '/dashboards/$dashboardId'
    | '/dashboards/add'
    | '/data-management/import'
    | '/mappings/$mappingId'
    | '/mappings/add'
    | '/outputs-and-indicators/indicators'
    | '/outputs-and-indicators/outputs'
    | '/projects/$projectId'
    | '/shared/$token'
    | '/dashboards/'
    | '/mappings/'
    | '/projects/'
    | '/dashboards/$dashboardId/edit'
    | '/dashboards/$dashboardId/manage'
    | '/dashboards/$dashboardId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/baseline-mapping'
    | '/connections'
    | '/data-management'
    | '/data-quality'
    | '/indicator-visualization'
    | '/login'
    | '/outputs-and-indicators'
    | '/pricing'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/connections/$connectionId'
    | '/dashboards/$dashboardId'
    | '/dashboards/add'
    | '/data-management/import'
    | '/mappings/$mappingId'
    | '/mappings/add'
    | '/outputs-and-indicators/indicators'
    | '/outputs-and-indicators/outputs'
    | '/projects/$projectId'
    | '/shared/$token'
    | '/dashboards'
    | '/mappings'
    | '/projects'
    | '/dashboards/$dashboardId/edit'
    | '/dashboards/$dashboardId/manage'
    | '/dashboards/$dashboardId/preview'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/baseline-mapping'
    | '/connections'
    | '/data-management'
    | '/data-quality'
    | '/indicator-visualization'
    | '/login'
    | '/outputs-and-indicators'
    | '/pricing'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/connections/$connectionId'
    | '/dashboards/$dashboardId'
    | '/dashboards/add'
    | '/data-management/import'
    | '/mappings/$mappingId'
    | '/mappings/add'
    | '/outputs-and-indicators/indicators'
    | '/outputs-and-indicators/outputs'
    | '/projects/$projectId'
    | '/shared/$token'
    | '/dashboards/'
    | '/mappings/'
    | '/projects/'
    | '/dashboards/$dashboardId/edit'
    | '/dashboards/$dashboardId/manage'
    | '/dashboards/$dashboardId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BaselineMappingRoute: typeof BaselineMappingRoute
  ConnectionsRoute: typeof ConnectionsRouteWithChildren
  DataManagementRoute: typeof DataManagementRouteWithChildren
  DataQualityRoute: typeof DataQualityRoute
  IndicatorVisualizationRoute: typeof IndicatorVisualizationRoute
  LoginRoute: typeof LoginRoute
  OutputsAndIndicatorsRoute: typeof OutputsAndIndicatorsRouteWithChildren
  PricingRoute: typeof PricingRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRouteWithChildren
  DashboardsAddRoute: typeof DashboardsAddRoute
  MappingsMappingIdRoute: typeof MappingsMappingIdRoute
  MappingsAddRoute: typeof MappingsAddRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  SharedTokenRoute: typeof SharedTokenRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  MappingsIndexRoute: typeof MappingsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs-and-indicators': {
      id: '/outputs-and-indicators'
      path: '/outputs-and-indicators'
      fullPath: '/outputs-and-indicators'
      preLoaderRoute: typeof OutputsAndIndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicator-visualization': {
      id: '/indicator-visualization'
      path: '/indicator-visualization'
      fullPath: '/indicator-visualization'
      preLoaderRoute: typeof IndicatorVisualizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality': {
      id: '/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof DataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-management': {
      id: '/data-management'
      path: '/data-management'
      fullPath: '/data-management'
      preLoaderRoute: typeof DataManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline-mapping': {
      id: '/baseline-mapping'
      path: '/baseline-mapping'
      fullPath: '/baseline-mapping'
      preLoaderRoute: typeof BaselineMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappings/': {
      id: '/mappings/'
      path: '/mappings'
      fullPath: '/mappings/'
      preLoaderRoute: typeof MappingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs-and-indicators/outputs': {
      id: '/outputs-and-indicators/outputs'
      path: '/outputs'
      fullPath: '/outputs-and-indicators/outputs'
      preLoaderRoute: typeof OutputsAndIndicatorsOutputsRouteImport
      parentRoute: typeof OutputsAndIndicatorsRoute
    }
    '/outputs-and-indicators/indicators': {
      id: '/outputs-and-indicators/indicators'
      path: '/indicators'
      fullPath: '/outputs-and-indicators/indicators'
      preLoaderRoute: typeof OutputsAndIndicatorsIndicatorsRouteImport
      parentRoute: typeof OutputsAndIndicatorsRoute
    }
    '/mappings/add': {
      id: '/mappings/add'
      path: '/mappings/add'
      fullPath: '/mappings/add'
      preLoaderRoute: typeof MappingsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappings/$mappingId': {
      id: '/mappings/$mappingId'
      path: '/mappings/$mappingId'
      fullPath: '/mappings/$mappingId'
      preLoaderRoute: typeof MappingsMappingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-management/import': {
      id: '/data-management/import'
      path: '/import'
      fullPath: '/data-management/import'
      preLoaderRoute: typeof DataManagementImportRouteImport
      parentRoute: typeof DataManagementRoute
    }
    '/dashboards/add': {
      id: '/dashboards/add'
      path: '/dashboards/add'
      fullPath: '/dashboards/add'
      preLoaderRoute: typeof DashboardsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$connectionId': {
      id: '/connections/$connectionId'
      path: '/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof ConnectionsConnectionIdRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/dashboards/$dashboardId/preview': {
      id: '/dashboards/$dashboardId/preview'
      path: '/preview'
      fullPath: '/dashboards/$dashboardId/preview'
      preLoaderRoute: typeof DashboardsDashboardIdPreviewRouteImport
      parentRoute: typeof DashboardsDashboardIdRoute
    }
    '/dashboards/$dashboardId/manage': {
      id: '/dashboards/$dashboardId/manage'
      path: '/manage'
      fullPath: '/dashboards/$dashboardId/manage'
      preLoaderRoute: typeof DashboardsDashboardIdManageRouteImport
      parentRoute: typeof DashboardsDashboardIdRoute
    }
    '/dashboards/$dashboardId/edit': {
      id: '/dashboards/$dashboardId/edit'
      path: '/edit'
      fullPath: '/dashboards/$dashboardId/edit'
      preLoaderRoute: typeof DashboardsDashboardIdEditRouteImport
      parentRoute: typeof DashboardsDashboardIdRoute
    }
  }
}

interface ConnectionsRouteChildren {
  ConnectionsConnectionIdRoute: typeof ConnectionsConnectionIdRoute
}

const ConnectionsRouteChildren: ConnectionsRouteChildren = {
  ConnectionsConnectionIdRoute: ConnectionsConnectionIdRoute,
}

const ConnectionsRouteWithChildren = ConnectionsRoute._addFileChildren(
  ConnectionsRouteChildren,
)

interface DataManagementRouteChildren {
  DataManagementImportRoute: typeof DataManagementImportRoute
}

const DataManagementRouteChildren: DataManagementRouteChildren = {
  DataManagementImportRoute: DataManagementImportRoute,
}

const DataManagementRouteWithChildren = DataManagementRoute._addFileChildren(
  DataManagementRouteChildren,
)

interface OutputsAndIndicatorsRouteChildren {
  OutputsAndIndicatorsIndicatorsRoute: typeof OutputsAndIndicatorsIndicatorsRoute
  OutputsAndIndicatorsOutputsRoute: typeof OutputsAndIndicatorsOutputsRoute
}

const OutputsAndIndicatorsRouteChildren: OutputsAndIndicatorsRouteChildren = {
  OutputsAndIndicatorsIndicatorsRoute: OutputsAndIndicatorsIndicatorsRoute,
  OutputsAndIndicatorsOutputsRoute: OutputsAndIndicatorsOutputsRoute,
}

const OutputsAndIndicatorsRouteWithChildren =
  OutputsAndIndicatorsRoute._addFileChildren(OutputsAndIndicatorsRouteChildren)

interface DashboardsDashboardIdRouteChildren {
  DashboardsDashboardIdEditRoute: typeof DashboardsDashboardIdEditRoute
  DashboardsDashboardIdManageRoute: typeof DashboardsDashboardIdManageRoute
  DashboardsDashboardIdPreviewRoute: typeof DashboardsDashboardIdPreviewRoute
}

const DashboardsDashboardIdRouteChildren: DashboardsDashboardIdRouteChildren = {
  DashboardsDashboardIdEditRoute: DashboardsDashboardIdEditRoute,
  DashboardsDashboardIdManageRoute: DashboardsDashboardIdManageRoute,
  DashboardsDashboardIdPreviewRoute: DashboardsDashboardIdPreviewRoute,
}

const DashboardsDashboardIdRouteWithChildren =
  DashboardsDashboardIdRoute._addFileChildren(
    DashboardsDashboardIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BaselineMappingRoute: BaselineMappingRoute,
  ConnectionsRoute: ConnectionsRouteWithChildren,
  DataManagementRoute: DataManagementRouteWithChildren,
  DataQualityRoute: DataQualityRoute,
  IndicatorVisualizationRoute: IndicatorVisualizationRoute,
  LoginRoute: LoginRoute,
  OutputsAndIndicatorsRoute: OutputsAndIndicatorsRouteWithChildren,
  PricingRoute: PricingRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRouteWithChildren,
  DashboardsAddRoute: DashboardsAddRoute,
  MappingsMappingIdRoute: MappingsMappingIdRoute,
  MappingsAddRoute: MappingsAddRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SharedTokenRoute: SharedTokenRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  MappingsIndexRoute: MappingsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
